import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service — Omni Loop Portal" };

export default function TermsPage() {
  return (
    <div className="page">
      <div className="container" style={{ maxWidth: 760 }}>
        <article className="docs-content fade-up">
          <span className="eyebrow">legal</span>
          <h1 style={{ marginTop: 18 }}>Terms of Service</h1>
          <p>Last updated: June 12, 2026</p>

          <h2>1. The service</h2>
          <p>
            The Omni Loop Portal (&quot;the Service&quot;), operated by Omni Loop
            Research Labs (&quot;we&quot;), is a subscription gateway that connects the
            open-source Clioloop agent to third-party AI models and tool services. The
            Service is exclusively for use with the Clioloop agent; standalone API
            access is not offered.
          </p>

          <h2>2. Accounts</h2>
          <p>
            You must provide a valid email address and keep your credentials secure.
            You are responsible for all activity on your account and connected
            devices. You can disconnect devices at any time from your account; we may
            suspend accounts that violate these terms.
          </p>

          <h2>3. Subscriptions &amp; billing</h2>
          <p>
            Paid plans renew monthly via Stripe until cancelled. You can cancel
            anytime; access continues until the end of the paid period. The Free plan
            requires a one-time card verification (a €0 authorization — never
            charged). Prices include applicable VAT where required.
          </p>

          <h2>4. Usage allowances</h2>
          <p>
            Each plan includes a monthly usage allowance covering model inference and
            tool-gateway calls, metered at our cost from upstream providers. Unused
            allowance does not roll over. When an allowance is exhausted, service
            pauses until the next monthly reset or a plan upgrade. We may apply fair
            -use limits to protect the Service.
          </p>

          <h2>5. Acceptable use</h2>
          <p>
            Don&apos;t use the Service for unlawful activity, to violate third-party
            rights, to circumvent metering or security, or to resell access. Output
            from AI models is generated by third-party providers and may be
            inaccurate — you are responsible for how you use it.
          </p>

          <h2>6. Availability &amp; liability</h2>
          <p>
            The Service is provided &quot;as is&quot; without warranties. Upstream model
            and tool providers may change or become unavailable outside our control.
            To the maximum extent permitted by law, our liability is limited to the
            fees you paid in the month the claim arose.
          </p>

          <h2>7. Changes</h2>
          <p>
            We may update these terms; material changes are announced by email or on
            this page at least 14 days in advance. Continued use after the effective
            date constitutes acceptance.
          </p>

          <h2>8. Contact</h2>
          <p>
            Questions: <a href="mailto:noreply@clioloop.com">noreply@clioloop.com</a>
          </p>
        </article>
      </div>
    </div>
  );
}
