#!/usr/bin/env python3
"""Generate deterministic config, command and plugin reference pages."""
from __future__ import annotations
import argparse, re, sys
from pathlib import Path

HEADER = "<!-- Generated by scripts/generate_references.py; do not edit. -->\n"

def config_keys(path: Path) -> list[tuple[str, str]]:
    stack: list[tuple[int,str]]=[]; found=[]
    for raw in path.read_text(encoding="utf-8").splitlines():
        line=raw.split("#",1)[0].rstrip()
        if not line.strip() or line.lstrip().startswith("-"): continue
        m=re.match(r"^(\s*)([A-Za-z0-9_.-]+):\s*(.*)$",line)
        if not m: continue
        indent=len(m.group(1)); key=m.group(2); value=m.group(3)
        while stack and stack[-1][0] >= indent: stack.pop()
        dotted=".".join([x[1] for x in stack]+[key])
        if value: found.append((dotted,value))
        else: stack.append((indent,key))
    return found

def command_names(root: Path) -> list[str]:
    names=set()
    for path in [root/"clio_cli/_parser.py", root/"clio_cli/main.py"]:
        text=path.read_text(encoding="utf-8")
        names.update(re.findall(r"add_parser\(\s*[\"']([^\"']+)[\"']",text))
    return sorted(names)

def plugins(root: Path) -> list[tuple[str,list[str]]]:
    out=[]
    for path in sorted((root/"plugins").rglob("__init__.py")):
        text=path.read_text(encoding="utf-8", errors="replace")
        registrations=sorted(set(re.findall(r"(?:ctx\.)?(register_[a-z_]+)\s*\(",text)))
        if "def register(" in text or registrations:
            out.append((str(path.parent.relative_to(root/"plugins")), registrations))
    return out

def render(root: Path) -> dict[Path,str]:
    config=["# Configuration reference", "", "Source: `cli-config.yaml.example`.", "", "| Key | Example/default |", "| --- | --- |"]
    for key, value in config_keys(root / "cli-config.yaml.example"):
        config.append(f"| `{key}` | `{value.replace(chr(96), '')}` |")
    commands=["# Command reference", "", "Commands are discovered from Clio's argparse registrations.", ""] + [f"- `clio {name}`" for name in command_names(root)]
    plugin=["# Plugin reference", "", "Python plugin entry points and static registration calls.", "", "| Plugin | Registrations |", "| --- | --- |"]
    plugin += [f"| `{name}` | {', '.join(f'`{r}`' for r in regs) or '`register`'} |" for name,regs in plugins(root)]
    return {root/"docs/generated/config-reference.md":HEADER+"\n".join(config)+"\n", root/"docs/generated/command-reference.md":HEADER+"\n".join(commands)+"\n", root/"docs/generated/plugin-reference.md":HEADER+"\n".join(plugin)+"\n"}

def main() -> int:
    ap=argparse.ArgumentParser(); ap.add_argument("--check",action="store_true"); ap.add_argument("--root",type=Path,default=Path(".")); args=ap.parse_args(); root=args.root.resolve(); errors=[]
    for path,content in render(root).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8")!=content: errors.append(f"stale generated reference: {path.relative_to(root)}")
        else:
            path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content, encoding="utf-8")
    print("\n".join(errors) if errors else ("generated references: current" if args.check else "generated references: updated"))
    return bool(errors)
if __name__ == "__main__": sys.exit(main())
