#!/usr/bin/env python3
"""
Gmail Tool Module — Full Gmail API access with auto-refreshing OAuth tokens.

Provides read, search, send, draft, label, and modify operations against the
Gmail API.  Token refresh is automatic: on every call the token is checked and
refreshed if expired before the API request is made.

Requirements:
    - ~/.clio/gmail/credentials.json  (Desktop OAuth client secrets from Google Cloud)
    - ~/.clio/gmail/token.json        (generated by the OAuth flow)
    - google-api-python-client, google-auth-httplib2, google-auth-oauthlib installed

Setup:
    Run ``python3 ~/.clio/gmail/gmail_auth.py`` once to authorise and generate
    token.json.  The tool handles the rest, including refresh.
"""

import json
import logging
import os
import threading
import time
import base64
from pathlib import Path
from typing import Optional

from tools.registry import registry

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths and constants
# ---------------------------------------------------------------------------

_GMAIL_DIR = Path(os.path.expanduser("~/.clio/gmail"))
_CRED_PATH = _GMAIL_DIR / "credentials.json"
_SCOPES = ["https://mail.google.com/"]

# Multi-account token paths: "1"-"3"
_TOKEN_PATHS = {
    "1": _GMAIL_DIR / "token.json",
    "2": _GMAIL_DIR / "token2.json",
    "3": _GMAIL_DIR / "token3.json",
}
# Default token path for backwards compatibility
_TOKEN_PATH = _TOKEN_PATHS["1"]

# Thread lock to prevent concurrent refresh races.
_token_lock = threading.Lock()

# ---------------------------------------------------------------------------
# Token management with auto-refresh
# ---------------------------------------------------------------------------

def _load_credentials(account: str = "1"):
    """Load credentials from the token file for the given account, refreshing if expired.

    Returns a valid Credentials object or raises RuntimeError.
    """
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials

    account = account or "1"
    if account not in _TOKEN_PATHS:
        available = ", ".join(sorted(_TOKEN_PATHS))
        raise RuntimeError(
            f"Gmail account {account!r} is not configured. "
            f"Available account numbers: {available}."
        )

    token_path = _TOKEN_PATHS[account]
    if not token_path.exists():
        raise RuntimeError(
            f"Gmail token not found at {token_path}. "
            f"Run: python3 ~/.clio/gmail/gmail_auth.py (account {account})"
        )

    creds = Credentials.from_authorized_user_file(str(token_path), _SCOPES)

    # If expired but we have a refresh token, refresh it now.
    if not creds.valid and creds.expired and creds.refresh_token:
        with _token_lock:
            # Double-check after acquiring lock (another thread may have refreshed).
            creds = Credentials.from_authorized_user_file(str(token_path), _SCOPES)
            if not creds.valid and creds.expired and creds.refresh_token:
                logger.info(f"Gmail token expired (account {account}) — refreshing...")
                creds.refresh(Request())
                # Persist the refreshed token.
                token_path.write_text(creds.to_json(), encoding="utf-8")
                os.chmod(token_path, 0o600)
                logger.info(f"Gmail token refreshed and saved (account {account}).")

    if not creds.valid:
        raise RuntimeError(
            f"Gmail token is invalid and cannot be refreshed (account {account}). "
            "Re-authorise: python3 ~/.clio/gmail/gmail_auth.py"
        )

    return creds


def _get_service(account: str = "1"):
    """Build and return a Gmail API service object with valid credentials."""
    from googleapiclient.discovery import build
    creds = _load_credentials(account)
    return build("gmail", "v1", credentials=creds, cache_discovery=False)


def _check_gmail_requirements() -> bool:
    """Check whether Gmail tool prerequisites are met (at least one account)."""
    try:
        return _CRED_PATH.exists() and any(p.exists() for p in _TOKEN_PATHS.values())
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def _decode_body(payload: dict) -> str:
    """Extract and decode the text body from a Gmail message payload."""
    parts = []
    if "body" in payload and payload["body"].get("data"):
        data = payload["body"]["data"]
        # URL-safe base64
        padded = data + "=" * (4 - len(data) % 4)
        try:
            decoded = base64.urlsafe_b64decode(padded).decode("utf-8", errors="replace")
            parts.append(decoded)
        except Exception:
            pass

    if "parts" in payload:
        for part in payload["parts"]:
            mime = part.get("mimeType", "")
            if mime == "text/plain" and part.get("body", {}).get("data"):
                data = part["body"]["data"]
                padded = data + "=" * (4 - len(data) % 4)
                try:
                    decoded = base64.urlsafe_b64decode(padded).decode("utf-8", errors="replace")
                    parts.append(decoded)
                except Exception:
                    pass
            elif mime == "multipart/alternative":
                # Recurse into alternative parts
                inner = _decode_body(part)
                if inner:
                    parts.append(inner)

    return "\n".join(parts) if parts else ""


def _extract_headers(msg: dict) -> dict:
    """Extract key headers from a Gmail message."""
    headers = {}
    for h in msg.get("payload", {}).get("headers", []):
        name = h.get("name", "").lower()
        headers[name] = h.get("value", "")
    return headers


def _summarize_message(msg: dict, include_body: bool = False) -> dict:
    """Turn a Gmail API message dict into a clean summary."""
    headers = _extract_headers(msg)
    result = {
        "id": msg.get("id"),
        "thread_id": msg.get("threadId"),
        "from": headers.get("from", ""),
        "to": headers.get("to", ""),
        "subject": headers.get("subject", ""),
        "date": headers.get("date", ""),
        "snippet": msg.get("snippet", ""),
        "label_ids": msg.get("labelIds", []),
    }
    if include_body:
        result["body"] = _decode_body(msg.get("payload", {}))
    return result


# ---------------------------------------------------------------------------
# Tool actions
# ---------------------------------------------------------------------------

def gmail_tool(action: str, query: str = "", max_results: int = 10,
                message_id: str = "", thread_id: str = "", label_id: str = "",
                to: str = "", subject: str = "", body: str = "", html: str = "",
                cc: str = "", bcc: str = "", label_name: str = "",
                add_labels: list = None, remove_labels: list = None,
                draft_id: str = "", file_paths: list = None,
                account: str = "1", **kwargs) -> str:
    """Unified Gmail tool — perform any Gmail action.

    Account selection:
        account="1"  — geerdwedda@gmail.com
        account="2"  — juniorwedda@gmail.com
        account="3"  — piorwedda@gmail.com
        If account is empty or "1", uses the default account.

    Actions:
        list          — List recent messages (max_results, optional label_id)
        search        — Search with Gmail query syntax (query, max_results)
        read          — Read a single message full body (message_id)
        read_thread   — Read all messages in a thread (thread_id)
        send          — Send an email (to, subject, body, optional cc/bcc/html/attachments)
        reply         — Reply to a thread (thread_id, body, optional html)
        create_draft — Create a draft (to, subject, body)
        send_draft    — Send an existing draft (draft_id)
        list_drafts   — List drafts (max_results)
        list_labels   — List all labels
        create_label  — Create a label (label_name)
        modify         — Modify message labels (message_id, add_labels, remove_labels)
        archive        — Archive a message (message_id) — removes INBOX label
        trash          — Move message to trash (message_id)
        untrash        — Remove message from trash (message_id)
        delete         — Permanently delete a message (message_id)
        mark_read      — Mark message as read (message_id)
        mark_unread    — Mark message as unread (message_id)
        star           — Star a message (message_id)
        unstar         — Remove star from a message (message_id)
        get_profile    — Get Gmail profile info
    """
    try:
        # Normalize account: empty or "1" -> default
        if not account or account == "1":
            account = "1"
        service = _get_service(account)
        users = service.users()

        # --- LIST recent messages ---
        if action == "list":
            list_kwargs = {"userId": "me", "maxResults": min(max_results, 100)}
            if label_id:
                list_kwargs["labelIds"] = [label_id]
            result = users.messages().list(**list_kwargs).execute()
            messages = result.get("messages", [])
            if not messages:
                return json.dumps({"success": True, "messages": [], "count": 0})

            # Batch fetch summaries
            out = []
            for m in messages[:max_results]:
                msg = users.messages().get(userId="me", id=m["id"], format="metadata",
                                           metadataHeaders=["From", "To", "Subject", "Date"]).execute()
                out.append(_summarize_message(msg))
            return json.dumps({"success": True, "messages": out, "count": len(out)}, ensure_ascii=False)

        # --- SEARCH ---
        if action == "search":
            if not query:
                return json.dumps({"error": "query is required for search"})
            result = users.messages().list(userId="me", q=query,
                                            maxResults=min(max_results, 100)).execute()
            messages = result.get("messages", [])
            if not messages:
                return json.dumps({"success": True, "messages": [], "count": 0,
                                   "query": query})
            out = []
            for m in messages[:max_results]:
                msg = users.messages().get(userId="me", id=m["id"], format="metadata",
                                           metadataHeaders=["From", "To", "Subject", "Date"]).execute()
                out.append(_summarize_message(msg))
            return json.dumps({"success": True, "messages": out, "count": len(out),
                               "query": query}, ensure_ascii=False)

        # --- READ single message ---
        if action == "read":
            if not message_id:
                return json.dumps({"error": "message_id is required for read"})
            msg = users.messages().get(userId="me", id=message_id, format="full").execute()
            summary = _summarize_message(msg, include_body=True)
            return json.dumps({"success": True, "message": summary}, ensure_ascii=False)

        # --- READ THREAD ---
        if action == "read_thread":
            if not thread_id:
                return json.dumps({"error": "thread_id is required for read_thread"})
            thread = users.threads().get(userId="me", id=thread_id, format="full").execute()
            messages_out = []
            for m in thread.get("messages", []):
                messages_out.append(_summarize_message(m, include_body=True))
            return json.dumps({"success": True, "thread_id": thread_id,
                               "messages": messages_out, "count": len(messages_out)},
                              ensure_ascii=False)

        # --- SEND ---
        if action == "send":
            if not to:
                return json.dumps({"error": "to is required for send"})
            if not subject and not body:
                return json.dumps({"error": "subject or body is required for send"})

            msg_parts = []
            msg_parts.append(f"To: {to}")
            if cc:
                msg_parts.append(f"Cc: {cc}")
            if bcc:
                msg_parts.append(f"Bcc: {bcc}")
            msg_parts.append(f"Subject: {subject}")

            # Build multipart message if HTML provided
            if html:
                boundary = "clio_gmail_boundary_12345"
                msg_parts.append(f'Content-Type: multipart/alternative; boundary="{boundary}"')
                msg_parts.append("")
                msg_parts.append(f"--{boundary}")
                msg_parts.append("Content-Type: text/plain; charset=utf-8")
                msg_parts.append("")
                msg_parts.append(body or "")
                msg_parts.append(f"--{boundary}")
                msg_parts.append("Content-Type: text/html; charset=utf-8")
                msg_parts.append("")
                msg_parts.append(html)
                msg_parts.append(f"--{boundary}--")
            else:
                msg_parts.append("Content-Type: text/plain; charset=utf-8")
                msg_parts.append("")
                msg_parts.append(body or "")

            raw = "\r\n".join(msg_parts)
            encoded = base64.urlsafe_b64encode(raw.encode("utf-8")).decode("ascii")
            sent = users.messages().send(userId="me",
                                          body={"raw": encoded}).execute()
            return json.dumps({"success": True, "message_id": sent.get("id"),
                               "thread_id": sent.get("threadId"),
                               "status": "sent"}, ensure_ascii=False)

        # --- REPLY to thread ---
        if action == "reply":
            if not thread_id:
                return json.dumps({"error": "thread_id is required for reply"})
            if not body:
                return json.dumps({"error": "body is required for reply"})

            # Get the thread to find original message headers
            thread = users.threads().get(userId="me", id=thread_id, format="metadata").execute()
            original = thread.get("messages", [{}])[0]
            orig_headers = _extract_headers(original)

            msg_parts = []
            if orig_headers.get("to"):
                msg_parts.append(f"To: {orig_headers['to']}")
            else:
                msg_parts.append(f"To: {to}")
            if orig_headers.get("subject"):
                if orig_headers["subject"].lower().startswith("re:"):
                    msg_parts.append(f"Subject: {orig_headers['subject']}")
                else:
                    msg_parts.append(f"Subject: Re: {orig_headers['subject']}")
            else:
                msg_parts.append(f"Subject: {subject}")
            msg_parts.append(f"In-Reply-To: {orig_headers.get('message-id', '')}")
            if orig_headers.get("references"):
                msg_parts.append(f"References: {orig_headers['references']}")
            msg_parts.append("Content-Type: text/plain; charset=utf-8")
            msg_parts.append("")
            msg_parts.append(body)

            raw = "\r\n".join(msg_parts)
            encoded = base64.urlsafe_b64encode(raw.encode("utf-8")).decode("ascii")
            sent = users.messages().send(userId="me",
                                          body={"raw": encoded,
                                                "threadId": thread_id}).execute()
            return json.dumps({"success": True, "message_id": sent.get("id"),
                               "thread_id": sent.get("threadId"),
                               "status": "replied"}, ensure_ascii=False)

        # --- CREATE DRAFT ---
        if action == "create_draft":
            if not to or not subject:
                return json.dumps({"error": "to and subject are required for create_draft"})
            msg_parts = [
                f"To: {to}",
                f"Subject: {subject}",
                "Content-Type: text/plain; charset=utf-8",
                "",
                body or "",
            ]
            raw = "\r\n".join(msg_parts)
            encoded = base64.urlsafe_b64encode(raw.encode("utf-8")).decode("ascii")
            draft = users.drafts().create(userId="me",
                                           body={"message": {"raw": encoded}}).execute()
            return json.dumps({"success": True, "draft_id": draft.get("id"),
                               "message_id": draft.get("message", {}).get("id")},
                              ensure_ascii=False)

        # --- SEND DRAFT ---
        if action == "send_draft":
            if not draft_id:
                return json.dumps({"error": "draft_id is required for send_draft"})
            sent = users.drafts().send(userId="me", id=draft_id,
                                        body={}).execute()
            return json.dumps({"success": True, "message_id": sent.get("id"),
                               "thread_id": sent.get("threadId"),
                               "status": "sent"}, ensure_ascii=False)

        # --- LIST DRAFTS ---
        if action == "list_drafts":
            result = users.drafts().list(userId="me",
                                          maxResults=min(max_results, 100)).execute()
            drafts = result.get("drafts", [])
            out = []
            for d in drafts[:max_results]:
                msg = users.drafts().get(userId="me", id=d["id"], format="metadata").execute()
                msg_headers = _extract_headers(msg.get("message", {}))
                out.append({
                    "draft_id": d["id"],
                    "message_id": d.get("message", {}).get("id"),
                    "to": msg_headers.get("to", ""),
                    "subject": msg_headers.get("subject", ""),
                })
            return json.dumps({"success": True, "drafts": out, "count": len(out)},
                              ensure_ascii=False)

        # --- LIST LABELS ---
        if action == "list_labels":
            result = users.labels().list(userId="me").execute()
            labels = result.get("labels", [])
            out = [{"id": l["id"], "name": l["name"], "type": l.get("type", "")}
                   for l in labels]
            return json.dumps({"success": True, "labels": out, "count": len(out)},
                              ensure_ascii=False)

        # --- CREATE LABEL ---
        if action == "create_label":
            if not label_name:
                return json.dumps({"error": "label_name is required for create_label"})
            label = users.labels().create(userId="me",
                                           body={"name": label_name}).execute()
            return json.dumps({"success": True, "label_id": label.get("id"),
                               "label_name": label.get("name")}, ensure_ascii=False)

        # --- MODIFY labels ---
        if action == "modify":
            if not message_id:
                return json.dumps({"error": "message_id is required for modify"})
            body = {}
            if add_labels:
                body["addLabelIds"] = add_labels
            if remove_labels:
                body["removeLabelIds"] = remove_labels
            if not body:
                return json.dumps({"error": "add_labels or remove_labels required for modify"})
            users.messages().modify(userId="me", id=message_id, body=body).execute()
            return json.dumps({"success": True, "message_id": message_id,
                               "action": "modified"}, ensure_ascii=False)

        # --- ARCHIVE ---
        if action == "archive":
            if not message_id:
                return json.dumps({"error": "message_id is required"})
            users.messages().modify(userId="me", id=message_id,
                                     body={"removeLabelIds": ["INBOX"]}).execute()
            return json.dumps({"success": True, "message_id": message_id,
                               "action": "archived"}, ensure_ascii=False)

        # --- TRASH ---
        if action == "trash":
            if not message_id:
                return json.dumps({"error": "message_id is required"})
            users.messages().trash(userId="me", id=message_id).execute()
            return json.dumps({"success": True, "message_id": message_id,
                               "action": "trashed"}, ensure_ascii=False)

        # --- UNTRASH ---
        if action == "untrash":
            if not message_id:
                return json.dumps({"error": "message_id is required"})
            users.messages().untrash(userId="me", id=message_id).execute()
            return json.dumps({"success": True, "message_id": message_id,
                               "action": "untrashed"}, ensure_ascii=False)

        # --- DELETE permanently ---
        if action == "delete":
            if not message_id:
                return json.dumps({"error": "message_id is required"})
            users.messages().delete(userId="me", id=message_id).execute()
            return json.dumps({"success": True, "message_id": message_id,
                               "action": "permanently_deleted"}, ensure_ascii=False)

        # --- MARK READ ---
        if action == "mark_read":
            if not message_id:
                return json.dumps({"error": "message_id is required"})
            users.messages().modify(userId="me", id=message_id,
                                     body={"removeLabelIds": ["UNREAD"]}).execute()
            return json.dumps({"success": True, "message_id": message_id,
                               "action": "marked_read"}, ensure_ascii=False)

        # --- MARK UNREAD ---
        if action == "mark_unread":
            if not message_id:
                return json.dumps({"error": "message_id is required"})
            users.messages().modify(userId="me", id=message_id,
                                     body={"addLabelIds": ["UNREAD"]}).execute()
            return json.dumps({"success": True, "message_id": message_id,
                               "action": "marked_unread"}, ensure_ascii=False)

        # --- STAR ---
        if action == "star":
            if not message_id:
                return json.dumps({"error": "message_id is required"})
            users.messages().modify(userId="me", id=message_id,
                                     body={"addLabelIds": ["STARRED"]}).execute()
            return json.dumps({"success": True, "message_id": message_id,
                               "action": "starred"}, ensure_ascii=False)

        # --- UNSTAR ---
        if action == "unstar":
            if not message_id:
                return json.dumps({"error": "message_id is required"})
            users.messages().modify(userId="me", id=message_id,
                                     body={"removeLabelIds": ["STARRED"]}).execute()
            return json.dumps({"success": True, "message_id": message_id,
                               "action": "unstarred"}, ensure_ascii=False)

        # --- GET PROFILE ---
        if action == "get_profile":
            profile = users.getProfile(userId="me").execute()
            return json.dumps({"success": True,
                               "email": profile.get("emailAddress"),
                               "messages_total": profile.get("messagesTotal"),
                               "threads_total": profile.get("threadsTotal"),
                               "history_id": profile.get("historyId")}, ensure_ascii=False)

        return json.dumps({"error": f"Unknown action: {action}"})

    except Exception as e:
        logger.exception("Gmail tool error")
        return json.dumps({"error": str(e), "action": action}, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Schema and registration
# ---------------------------------------------------------------------------

GMAIL_SCHEMA = {
    "name": "gmail",
    "description": (
        "Full Gmail access: read, search, send, reply, draft, label, "
        "archive, trash, delete, mark read/unread, star, and get profile. "
        "OAuth token auto-refreshes when expired."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "description": (
                    "Gmail action to perform. One of: list, search, read, "
                    "read_thread, send, reply, create_draft, send_draft, "
                    "list_drafts, list_labels, create_label, modify, archive, "
                    "trash, untrash, delete, mark_read, mark_unread, star, "
                    "unstar, get_profile."
                ),
            },
            "query": {
                "type": "string",
                "description": "Gmail search query (for 'search' action). Uses Gmail query syntax: from:, to:, subject:, has:attachment, label:, is:unread, after:, before:, etc.",
            },
            "max_results": {
                "type": "integer",
                "description": "Maximum results to return (default 10). Used by list, search, list_drafts.",
                "default": 10,
            },
            "message_id": {
                "type": "string",
                "description": "Gmail message ID (for read, modify, archive, trash, delete, mark_read, mark_unread, star, unstar).",
            },
            "thread_id": {
                "type": "string",
                "description": "Gmail thread ID (for read_thread, reply).",
            },
            "label_id": {
                "type": "string",
                "description": "Label ID to filter list by (optional, for 'list' action).",
            },
            "to": {
                "type": "string",
                "description": "Recipient email address (for send, create_draft).",
            },
            "subject": {
                "type": "string",
                "description": "Email subject (for send, create_draft, reply).",
            },
            "body": {
                "type": "string",
                "description": "Email body text (for send, reply, create_draft).",
            },
            "html": {
                "type": "string",
                "description": "HTML body content (optional, for send). If provided, sends multipart/alternative.",
            },
            "cc": {
                "type": "string",
                "description": "CC recipients (for send).",
            },
            "bcc": {
                "type": "string",
                "description": "BCC recipients (for send).",
            },
            "label_name": {
                "type": "string",
                "description": "Label name (for create_label).",
            },
            "add_labels": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Label IDs to add (for modify).",
            },
            "remove_labels": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Label IDs to remove (for modify).",
            },
            "draft_id": {
                "type": "string",
                "description": "Draft ID (for send_draft).",
            },
            "account": {
                "type": "string",
                "description": "Gmail account to use: \"1\"=geerdwedda, \"2\"=juniorwedda, \"3\"=piorwedda. Defaults to \"1\".",
            },
        },
        "required": ["action"],
    },
}

registry.register(
    name="gmail",
    toolset="gmail",
    schema=GMAIL_SCHEMA,
    handler=lambda args, **kw: gmail_tool(
        action=args.get("action", ""),
        query=args.get("query", ""),
        max_results=args.get("max_results", 10),
        message_id=args.get("message_id", ""),
        thread_id=args.get("thread_id", ""),
        label_id=args.get("label_id", ""),
        to=args.get("to", ""),
        subject=args.get("subject", ""),
        body=args.get("body", ""),
        html=args.get("html", ""),
        cc=args.get("cc", ""),
        bcc=args.get("bcc", ""),
        label_name=args.get("label_name", ""),
        add_labels=args.get("add_labels"),
        remove_labels=args.get("remove_labels"),
        draft_id=args.get("draft_id", ""),
        account=args.get("account", "1"),
    ),
    check_fn=_check_gmail_requirements,
    emoji="📧",
)